### ISSUE TITLE
Can I join?

### ISSUE THREAD

**Issue by kyleplo** [SwiftSites/SwiftSites.github.io#14]
Can I join SwiftSites please? I know HTML, CSS, JavaScript, and some PHP. My website is kyleplogames.com

> Sorry if this is the wrong place to request

**Comment by radioblahaj** [comment]
@GreenBayRules

**Comment by Sheshank-s** [comment]
@kyleplo Sorry there has been lots of changes to swiftsites, we are still working lots of things out, and we don't really have the need for another person.
