### ISSUE TITLE
Marketing Plan?

### ISSUE THREAD

**Issue by ateesdalejr** [SwiftSites/SwiftSites.github.io#3]
Do you have a specific idea on how you'll market things? Go from local business to business that have horrible websites and offer to make them one for cheap? Also what happens when you start earning more than the minimum tax deductible value for a single person?

**Comment by Sheshank-s** [comment]
Well, I doubt that we will earn that much :D 

Right now we are just getting orders through Discord. Soon we will have better ways, right now we only have one order. This is something I'm going to assign @Nanomotion on right now, since @csf30816 and I are working on the order.

**Comment by Sheshank-s** [comment]
We actually now have a head of marketing in charge of this, I will assign him to answer your question, @ParaTecYT

**Comment by ParaTecYT** [comment]
What I am leaning towards right now is Forum posts, also Social media posts & follows. @ateesdalejr

**Comment by ateesdalejr** [comment]
@ParaTecYT You still haven't answered my second question.

**Comment by ParaTecYT** [comment]
I am still thinking let me get back to you on that.

**Comment by zspri** [comment]
"Go from local business to business that have horrible websites and offer to make them one for cheap?"
We're in it for the developing and practicing our skills, not for money. You're assuming that we're going to hire a crap-ton of people and not work with the clients well. Let's actually exist for more than a week before we worry about that.

**Comment by Sheshank-s** [comment]
Pretty much what Nanomotion said. This company is not made for the money, more for the experience.

**Comment by ateesdalejr** [comment]
Ah. :) Good luck then. 👍 If I see I can help with anything I'll try my best.
