### ISSUE TITLE
You can choose an unavailable theme

### ISSUE THREAD

**Issue by kerrtravers** [SwiftSites/SwiftSites.github.io#8]
![untitled](https://user-images.githubusercontent.com/26391179/34651560-b06ec268-f3c9-11e7-978a-62a3a25e3054.png)
(There isn't even a preview or card for this theme yet)

**Comment by Sheshank-s** [comment]
O bc we removed that theme since it sucks. You can make a pr for it

**Comment by kerrtravers** [comment]
Ah okay
